version: 0.1.0-{build}
image: Visual Studio 2017
configuration: Release

branches:
  only:
    - master

environment:
  COVERALLS_REPO_TOKEN:
    secure: YeKsMYgc+mNFE+yN5S0r5A6cY50tElPf0e8fIDhdDtdbZ8HWDHgOd5eejr/wO+Gy
  SONAR_TOKEN:
    secure: AjGMmrMXPnOITlyAZ36yaf+2UI3VsmliCuqVV859q8HM0qXS+Tbo0FSpJ1oDZJG5

build_script:
  - ps: Set-Location ./build
  - ps: ./build.ps1 -Target Full

artifacts:
  - path: 'build/artifacts/*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: dY59EPMAxx5HCinjuCF7JnnFIVaelfbM5l5DTY+kWIbhp17e/qUHFuyAJE/1tjQg
  skip_symbols: true
  artifact: /.*\.nupkg/
