// <auto-generated/>
//
// This file is generated from PrimitiveDelegates.tt - modify the template to
// make changes here.

namespace Crest.Host.Serialization
{
    using System;
    using System.Collections.Generic;
    using System.Reflection;
    using Crest.Host.Serialization.Internal;

    internal partial class DeserializeDelegateGenerator
    {
        private static readonly int[] MetadataIndexes = new int[18];

        private static void AddPrimitiveDelegates(IDictionary<Type, DeserializeInstance> dictionary, Func<MemberInfo, int> getMetadataIndex)
        {
            MetadataIndexes[0] = getMetadataIndex(typeof(Boolean));
            dictionary.Add(typeof(Boolean), ReadPrimitiveBoolean);
            dictionary.Add(typeof(Boolean?), ReadPrimitiveNullableBoolean);
            MetadataIndexes[1] = getMetadataIndex(typeof(Byte));
            dictionary.Add(typeof(Byte), ReadPrimitiveByte);
            dictionary.Add(typeof(Byte?), ReadPrimitiveNullableByte);
            MetadataIndexes[2] = getMetadataIndex(typeof(Char));
            dictionary.Add(typeof(Char), ReadPrimitiveChar);
            dictionary.Add(typeof(Char?), ReadPrimitiveNullableChar);
            MetadataIndexes[3] = getMetadataIndex(typeof(Decimal));
            dictionary.Add(typeof(Decimal), ReadPrimitiveDecimal);
            dictionary.Add(typeof(Decimal?), ReadPrimitiveNullableDecimal);
            MetadataIndexes[4] = getMetadataIndex(typeof(Double));
            dictionary.Add(typeof(Double), ReadPrimitiveDouble);
            dictionary.Add(typeof(Double?), ReadPrimitiveNullableDouble);
            MetadataIndexes[5] = getMetadataIndex(typeof(Single));
            dictionary.Add(typeof(Single), ReadPrimitiveSingle);
            dictionary.Add(typeof(Single?), ReadPrimitiveNullableSingle);
            MetadataIndexes[6] = getMetadataIndex(typeof(Int32));
            dictionary.Add(typeof(Int32), ReadPrimitiveInt32);
            dictionary.Add(typeof(Int32?), ReadPrimitiveNullableInt32);
            MetadataIndexes[7] = getMetadataIndex(typeof(Int64));
            dictionary.Add(typeof(Int64), ReadPrimitiveInt64);
            dictionary.Add(typeof(Int64?), ReadPrimitiveNullableInt64);
            MetadataIndexes[8] = getMetadataIndex(typeof(SByte));
            dictionary.Add(typeof(SByte), ReadPrimitiveSByte);
            dictionary.Add(typeof(SByte?), ReadPrimitiveNullableSByte);
            MetadataIndexes[9] = getMetadataIndex(typeof(Int16));
            dictionary.Add(typeof(Int16), ReadPrimitiveInt16);
            dictionary.Add(typeof(Int16?), ReadPrimitiveNullableInt16);
            MetadataIndexes[10] = getMetadataIndex(typeof(String));
            dictionary.Add(typeof(String), ReadPrimitiveString);
            MetadataIndexes[11] = getMetadataIndex(typeof(UInt32));
            dictionary.Add(typeof(UInt32), ReadPrimitiveUInt32);
            dictionary.Add(typeof(UInt32?), ReadPrimitiveNullableUInt32);
            MetadataIndexes[12] = getMetadataIndex(typeof(UInt64));
            dictionary.Add(typeof(UInt64), ReadPrimitiveUInt64);
            dictionary.Add(typeof(UInt64?), ReadPrimitiveNullableUInt64);
            MetadataIndexes[13] = getMetadataIndex(typeof(UInt16));
            dictionary.Add(typeof(UInt16), ReadPrimitiveUInt16);
            dictionary.Add(typeof(UInt16?), ReadPrimitiveNullableUInt16);
            MetadataIndexes[14] = getMetadataIndex(typeof(DateTime));
            dictionary.Add(typeof(DateTime), ReadPrimitiveDateTime);
            dictionary.Add(typeof(DateTime?), ReadPrimitiveNullableDateTime);
            MetadataIndexes[15] = getMetadataIndex(typeof(Guid));
            dictionary.Add(typeof(Guid), ReadPrimitiveGuid);
            dictionary.Add(typeof(Guid?), ReadPrimitiveNullableGuid);
            MetadataIndexes[16] = getMetadataIndex(typeof(TimeSpan));
            dictionary.Add(typeof(TimeSpan), ReadPrimitiveTimeSpan);
            dictionary.Add(typeof(TimeSpan?), ReadPrimitiveNullableTimeSpan);
            MetadataIndexes[17] = getMetadataIndex(typeof(Uri));
            dictionary.Add(typeof(Uri), ReadPrimitiveUri);
        }

        private static object ReadPrimitiveBoolean(IFormatter formatter, IReadOnlyList<object> metadata)
        {
            formatter.ReadBeginPrimitive(metadata[MetadataIndexes[0]]);
            object instance = formatter.Reader.ReadBoolean();
            formatter.ReadEndPrimitive();
            return instance;
        }

        private static object ReadPrimitiveNullableBoolean(IFormatter formatter, IReadOnlyList<object> metadata)
        {
            object instance = null;
            if (!formatter.Reader.ReadNull())
            {
                formatter.ReadBeginPrimitive(metadata[MetadataIndexes[0]]);
                instance = (object)formatter.Reader.ReadBoolean();
                formatter.ReadEndPrimitive();
            }

            return instance;
        }

        private static object ReadPrimitiveByte(IFormatter formatter, IReadOnlyList<object> metadata)
        {
            formatter.ReadBeginPrimitive(metadata[MetadataIndexes[1]]);
            object instance = formatter.Reader.ReadByte();
            formatter.ReadEndPrimitive();
            return instance;
        }

        private static object ReadPrimitiveNullableByte(IFormatter formatter, IReadOnlyList<object> metadata)
        {
            object instance = null;
            if (!formatter.Reader.ReadNull())
            {
                formatter.ReadBeginPrimitive(metadata[MetadataIndexes[1]]);
                instance = (object)formatter.Reader.ReadByte();
                formatter.ReadEndPrimitive();
            }

            return instance;
        }

        private static object ReadPrimitiveChar(IFormatter formatter, IReadOnlyList<object> metadata)
        {
            formatter.ReadBeginPrimitive(metadata[MetadataIndexes[2]]);
            object instance = formatter.Reader.ReadChar();
            formatter.ReadEndPrimitive();
            return instance;
        }

        private static object ReadPrimitiveNullableChar(IFormatter formatter, IReadOnlyList<object> metadata)
        {
            object instance = null;
            if (!formatter.Reader.ReadNull())
            {
                formatter.ReadBeginPrimitive(metadata[MetadataIndexes[2]]);
                instance = (object)formatter.Reader.ReadChar();
                formatter.ReadEndPrimitive();
            }

            return instance;
        }

        private static object ReadPrimitiveDecimal(IFormatter formatter, IReadOnlyList<object> metadata)
        {
            formatter.ReadBeginPrimitive(metadata[MetadataIndexes[3]]);
            object instance = formatter.Reader.ReadDecimal();
            formatter.ReadEndPrimitive();
            return instance;
        }

        private static object ReadPrimitiveNullableDecimal(IFormatter formatter, IReadOnlyList<object> metadata)
        {
            object instance = null;
            if (!formatter.Reader.ReadNull())
            {
                formatter.ReadBeginPrimitive(metadata[MetadataIndexes[3]]);
                instance = (object)formatter.Reader.ReadDecimal();
                formatter.ReadEndPrimitive();
            }

            return instance;
        }

        private static object ReadPrimitiveDouble(IFormatter formatter, IReadOnlyList<object> metadata)
        {
            formatter.ReadBeginPrimitive(metadata[MetadataIndexes[4]]);
            object instance = formatter.Reader.ReadDouble();
            formatter.ReadEndPrimitive();
            return instance;
        }

        private static object ReadPrimitiveNullableDouble(IFormatter formatter, IReadOnlyList<object> metadata)
        {
            object instance = null;
            if (!formatter.Reader.ReadNull())
            {
                formatter.ReadBeginPrimitive(metadata[MetadataIndexes[4]]);
                instance = (object)formatter.Reader.ReadDouble();
                formatter.ReadEndPrimitive();
            }

            return instance;
        }

        private static object ReadPrimitiveSingle(IFormatter formatter, IReadOnlyList<object> metadata)
        {
            formatter.ReadBeginPrimitive(metadata[MetadataIndexes[5]]);
            object instance = formatter.Reader.ReadSingle();
            formatter.ReadEndPrimitive();
            return instance;
        }

        private static object ReadPrimitiveNullableSingle(IFormatter formatter, IReadOnlyList<object> metadata)
        {
            object instance = null;
            if (!formatter.Reader.ReadNull())
            {
                formatter.ReadBeginPrimitive(metadata[MetadataIndexes[5]]);
                instance = (object)formatter.Reader.ReadSingle();
                formatter.ReadEndPrimitive();
            }

            return instance;
        }

        private static object ReadPrimitiveInt32(IFormatter formatter, IReadOnlyList<object> metadata)
        {
            formatter.ReadBeginPrimitive(metadata[MetadataIndexes[6]]);
            object instance = formatter.Reader.ReadInt32();
            formatter.ReadEndPrimitive();
            return instance;
        }

        private static object ReadPrimitiveNullableInt32(IFormatter formatter, IReadOnlyList<object> metadata)
        {
            object instance = null;
            if (!formatter.Reader.ReadNull())
            {
                formatter.ReadBeginPrimitive(metadata[MetadataIndexes[6]]);
                instance = (object)formatter.Reader.ReadInt32();
                formatter.ReadEndPrimitive();
            }

            return instance;
        }

        private static object ReadPrimitiveInt64(IFormatter formatter, IReadOnlyList<object> metadata)
        {
            formatter.ReadBeginPrimitive(metadata[MetadataIndexes[7]]);
            object instance = formatter.Reader.ReadInt64();
            formatter.ReadEndPrimitive();
            return instance;
        }

        private static object ReadPrimitiveNullableInt64(IFormatter formatter, IReadOnlyList<object> metadata)
        {
            object instance = null;
            if (!formatter.Reader.ReadNull())
            {
                formatter.ReadBeginPrimitive(metadata[MetadataIndexes[7]]);
                instance = (object)formatter.Reader.ReadInt64();
                formatter.ReadEndPrimitive();
            }

            return instance;
        }

        private static object ReadPrimitiveSByte(IFormatter formatter, IReadOnlyList<object> metadata)
        {
            formatter.ReadBeginPrimitive(metadata[MetadataIndexes[8]]);
            object instance = formatter.Reader.ReadSByte();
            formatter.ReadEndPrimitive();
            return instance;
        }

        private static object ReadPrimitiveNullableSByte(IFormatter formatter, IReadOnlyList<object> metadata)
        {
            object instance = null;
            if (!formatter.Reader.ReadNull())
            {
                formatter.ReadBeginPrimitive(metadata[MetadataIndexes[8]]);
                instance = (object)formatter.Reader.ReadSByte();
                formatter.ReadEndPrimitive();
            }

            return instance;
        }

        private static object ReadPrimitiveInt16(IFormatter formatter, IReadOnlyList<object> metadata)
        {
            formatter.ReadBeginPrimitive(metadata[MetadataIndexes[9]]);
            object instance = formatter.Reader.ReadInt16();
            formatter.ReadEndPrimitive();
            return instance;
        }

        private static object ReadPrimitiveNullableInt16(IFormatter formatter, IReadOnlyList<object> metadata)
        {
            object instance = null;
            if (!formatter.Reader.ReadNull())
            {
                formatter.ReadBeginPrimitive(metadata[MetadataIndexes[9]]);
                instance = (object)formatter.Reader.ReadInt16();
                formatter.ReadEndPrimitive();
            }

            return instance;
        }

        private static object ReadPrimitiveString(IFormatter formatter, IReadOnlyList<object> metadata)
        {
            object instance = null;
            if (!formatter.Reader.ReadNull())
            {
                formatter.ReadBeginPrimitive(metadata[MetadataIndexes[10]]);
                instance = (object)formatter.Reader.ReadString();
                formatter.ReadEndPrimitive();
            }

            return instance;
        }

        private static object ReadPrimitiveUInt32(IFormatter formatter, IReadOnlyList<object> metadata)
        {
            formatter.ReadBeginPrimitive(metadata[MetadataIndexes[11]]);
            object instance = formatter.Reader.ReadUInt32();
            formatter.ReadEndPrimitive();
            return instance;
        }

        private static object ReadPrimitiveNullableUInt32(IFormatter formatter, IReadOnlyList<object> metadata)
        {
            object instance = null;
            if (!formatter.Reader.ReadNull())
            {
                formatter.ReadBeginPrimitive(metadata[MetadataIndexes[11]]);
                instance = (object)formatter.Reader.ReadUInt32();
                formatter.ReadEndPrimitive();
            }

            return instance;
        }

        private static object ReadPrimitiveUInt64(IFormatter formatter, IReadOnlyList<object> metadata)
        {
            formatter.ReadBeginPrimitive(metadata[MetadataIndexes[12]]);
            object instance = formatter.Reader.ReadUInt64();
            formatter.ReadEndPrimitive();
            return instance;
        }

        private static object ReadPrimitiveNullableUInt64(IFormatter formatter, IReadOnlyList<object> metadata)
        {
            object instance = null;
            if (!formatter.Reader.ReadNull())
            {
                formatter.ReadBeginPrimitive(metadata[MetadataIndexes[12]]);
                instance = (object)formatter.Reader.ReadUInt64();
                formatter.ReadEndPrimitive();
            }

            return instance;
        }

        private static object ReadPrimitiveUInt16(IFormatter formatter, IReadOnlyList<object> metadata)
        {
            formatter.ReadBeginPrimitive(metadata[MetadataIndexes[13]]);
            object instance = formatter.Reader.ReadUInt16();
            formatter.ReadEndPrimitive();
            return instance;
        }

        private static object ReadPrimitiveNullableUInt16(IFormatter formatter, IReadOnlyList<object> metadata)
        {
            object instance = null;
            if (!formatter.Reader.ReadNull())
            {
                formatter.ReadBeginPrimitive(metadata[MetadataIndexes[13]]);
                instance = (object)formatter.Reader.ReadUInt16();
                formatter.ReadEndPrimitive();
            }

            return instance;
        }

        private static object ReadPrimitiveDateTime(IFormatter formatter, IReadOnlyList<object> metadata)
        {
            formatter.ReadBeginPrimitive(metadata[MetadataIndexes[14]]);
            object instance = formatter.Reader.ReadDateTime();
            formatter.ReadEndPrimitive();
            return instance;
        }

        private static object ReadPrimitiveNullableDateTime(IFormatter formatter, IReadOnlyList<object> metadata)
        {
            object instance = null;
            if (!formatter.Reader.ReadNull())
            {
                formatter.ReadBeginPrimitive(metadata[MetadataIndexes[14]]);
                instance = (object)formatter.Reader.ReadDateTime();
                formatter.ReadEndPrimitive();
            }

            return instance;
        }

        private static object ReadPrimitiveGuid(IFormatter formatter, IReadOnlyList<object> metadata)
        {
            formatter.ReadBeginPrimitive(metadata[MetadataIndexes[15]]);
            object instance = formatter.Reader.ReadGuid();
            formatter.ReadEndPrimitive();
            return instance;
        }

        private static object ReadPrimitiveNullableGuid(IFormatter formatter, IReadOnlyList<object> metadata)
        {
            object instance = null;
            if (!formatter.Reader.ReadNull())
            {
                formatter.ReadBeginPrimitive(metadata[MetadataIndexes[15]]);
                instance = (object)formatter.Reader.ReadGuid();
                formatter.ReadEndPrimitive();
            }

            return instance;
        }

        private static object ReadPrimitiveTimeSpan(IFormatter formatter, IReadOnlyList<object> metadata)
        {
            formatter.ReadBeginPrimitive(metadata[MetadataIndexes[16]]);
            object instance = formatter.Reader.ReadTimeSpan();
            formatter.ReadEndPrimitive();
            return instance;
        }

        private static object ReadPrimitiveNullableTimeSpan(IFormatter formatter, IReadOnlyList<object> metadata)
        {
            object instance = null;
            if (!formatter.Reader.ReadNull())
            {
                formatter.ReadBeginPrimitive(metadata[MetadataIndexes[16]]);
                instance = (object)formatter.Reader.ReadTimeSpan();
                formatter.ReadEndPrimitive();
            }

            return instance;
        }

        private static object ReadPrimitiveUri(IFormatter formatter, IReadOnlyList<object> metadata)
        {
            object instance = null;
            if (!formatter.Reader.ReadNull())
            {
                formatter.ReadBeginPrimitive(metadata[MetadataIndexes[17]]);
                instance = (object)formatter.Reader.ReadUri();
                formatter.ReadEndPrimitive();
            }

            return instance;
        }
    }

    internal partial class SerializeDelegateGenerator
    {
        private static readonly int[] MetadataIndexes = new int[18];

        private static void AddPrimitiveDelegates(IDictionary<Type, SerializeInstance> dictionary, Func<MemberInfo, int> getMetadataIndex)
        {
            MetadataIndexes[0] = getMetadataIndex(typeof(Boolean));
            dictionary.Add(typeof(Boolean), WritePrimitiveBoolean);
            dictionary.Add(typeof(Boolean?), WritePrimitiveBoolean);
            MetadataIndexes[1] = getMetadataIndex(typeof(Byte));
            dictionary.Add(typeof(Byte), WritePrimitiveByte);
            dictionary.Add(typeof(Byte?), WritePrimitiveByte);
            MetadataIndexes[2] = getMetadataIndex(typeof(Char));
            dictionary.Add(typeof(Char), WritePrimitiveChar);
            dictionary.Add(typeof(Char?), WritePrimitiveChar);
            MetadataIndexes[3] = getMetadataIndex(typeof(Decimal));
            dictionary.Add(typeof(Decimal), WritePrimitiveDecimal);
            dictionary.Add(typeof(Decimal?), WritePrimitiveDecimal);
            MetadataIndexes[4] = getMetadataIndex(typeof(Double));
            dictionary.Add(typeof(Double), WritePrimitiveDouble);
            dictionary.Add(typeof(Double?), WritePrimitiveDouble);
            MetadataIndexes[5] = getMetadataIndex(typeof(Single));
            dictionary.Add(typeof(Single), WritePrimitiveSingle);
            dictionary.Add(typeof(Single?), WritePrimitiveSingle);
            MetadataIndexes[6] = getMetadataIndex(typeof(Int32));
            dictionary.Add(typeof(Int32), WritePrimitiveInt32);
            dictionary.Add(typeof(Int32?), WritePrimitiveInt32);
            MetadataIndexes[7] = getMetadataIndex(typeof(Int64));
            dictionary.Add(typeof(Int64), WritePrimitiveInt64);
            dictionary.Add(typeof(Int64?), WritePrimitiveInt64);
            MetadataIndexes[8] = getMetadataIndex(typeof(SByte));
            dictionary.Add(typeof(SByte), WritePrimitiveSByte);
            dictionary.Add(typeof(SByte?), WritePrimitiveSByte);
            MetadataIndexes[9] = getMetadataIndex(typeof(Int16));
            dictionary.Add(typeof(Int16), WritePrimitiveInt16);
            dictionary.Add(typeof(Int16?), WritePrimitiveInt16);
            MetadataIndexes[10] = getMetadataIndex(typeof(String));
            dictionary.Add(typeof(String), WritePrimitiveString);
            MetadataIndexes[11] = getMetadataIndex(typeof(UInt32));
            dictionary.Add(typeof(UInt32), WritePrimitiveUInt32);
            dictionary.Add(typeof(UInt32?), WritePrimitiveUInt32);
            MetadataIndexes[12] = getMetadataIndex(typeof(UInt64));
            dictionary.Add(typeof(UInt64), WritePrimitiveUInt64);
            dictionary.Add(typeof(UInt64?), WritePrimitiveUInt64);
            MetadataIndexes[13] = getMetadataIndex(typeof(UInt16));
            dictionary.Add(typeof(UInt16), WritePrimitiveUInt16);
            dictionary.Add(typeof(UInt16?), WritePrimitiveUInt16);
            MetadataIndexes[14] = getMetadataIndex(typeof(DateTime));
            dictionary.Add(typeof(DateTime), WritePrimitiveDateTime);
            dictionary.Add(typeof(DateTime?), WritePrimitiveDateTime);
            MetadataIndexes[15] = getMetadataIndex(typeof(Guid));
            dictionary.Add(typeof(Guid), WritePrimitiveGuid);
            dictionary.Add(typeof(Guid?), WritePrimitiveGuid);
            MetadataIndexes[16] = getMetadataIndex(typeof(TimeSpan));
            dictionary.Add(typeof(TimeSpan), WritePrimitiveTimeSpan);
            dictionary.Add(typeof(TimeSpan?), WritePrimitiveTimeSpan);
            MetadataIndexes[17] = getMetadataIndex(typeof(Uri));
            dictionary.Add(typeof(Uri), WritePrimitiveUri);
        }

        private static void WritePrimitiveBoolean(IFormatter formatter, IReadOnlyList<object> metadata, object instance)
        {
            formatter.WriteBeginPrimitive(metadata[MetadataIndexes[0]]);
            formatter.Writer.WriteBoolean((Boolean)instance);
            formatter.WriteEndPrimitive();
        }

        private static void WritePrimitiveByte(IFormatter formatter, IReadOnlyList<object> metadata, object instance)
        {
            formatter.WriteBeginPrimitive(metadata[MetadataIndexes[1]]);
            formatter.Writer.WriteByte((Byte)instance);
            formatter.WriteEndPrimitive();
        }

        private static void WritePrimitiveChar(IFormatter formatter, IReadOnlyList<object> metadata, object instance)
        {
            formatter.WriteBeginPrimitive(metadata[MetadataIndexes[2]]);
            formatter.Writer.WriteChar((Char)instance);
            formatter.WriteEndPrimitive();
        }

        private static void WritePrimitiveDecimal(IFormatter formatter, IReadOnlyList<object> metadata, object instance)
        {
            formatter.WriteBeginPrimitive(metadata[MetadataIndexes[3]]);
            formatter.Writer.WriteDecimal((Decimal)instance);
            formatter.WriteEndPrimitive();
        }

        private static void WritePrimitiveDouble(IFormatter formatter, IReadOnlyList<object> metadata, object instance)
        {
            formatter.WriteBeginPrimitive(metadata[MetadataIndexes[4]]);
            formatter.Writer.WriteDouble((Double)instance);
            formatter.WriteEndPrimitive();
        }

        private static void WritePrimitiveSingle(IFormatter formatter, IReadOnlyList<object> metadata, object instance)
        {
            formatter.WriteBeginPrimitive(metadata[MetadataIndexes[5]]);
            formatter.Writer.WriteSingle((Single)instance);
            formatter.WriteEndPrimitive();
        }

        private static void WritePrimitiveInt32(IFormatter formatter, IReadOnlyList<object> metadata, object instance)
        {
            formatter.WriteBeginPrimitive(metadata[MetadataIndexes[6]]);
            formatter.Writer.WriteInt32((Int32)instance);
            formatter.WriteEndPrimitive();
        }

        private static void WritePrimitiveInt64(IFormatter formatter, IReadOnlyList<object> metadata, object instance)
        {
            formatter.WriteBeginPrimitive(metadata[MetadataIndexes[7]]);
            formatter.Writer.WriteInt64((Int64)instance);
            formatter.WriteEndPrimitive();
        }

        private static void WritePrimitiveSByte(IFormatter formatter, IReadOnlyList<object> metadata, object instance)
        {
            formatter.WriteBeginPrimitive(metadata[MetadataIndexes[8]]);
            formatter.Writer.WriteSByte((SByte)instance);
            formatter.WriteEndPrimitive();
        }

        private static void WritePrimitiveInt16(IFormatter formatter, IReadOnlyList<object> metadata, object instance)
        {
            formatter.WriteBeginPrimitive(metadata[MetadataIndexes[9]]);
            formatter.Writer.WriteInt16((Int16)instance);
            formatter.WriteEndPrimitive();
        }

        private static void WritePrimitiveString(IFormatter formatter, IReadOnlyList<object> metadata, object instance)
        {
            formatter.WriteBeginPrimitive(metadata[MetadataIndexes[10]]);
            formatter.Writer.WriteString((String)instance);
            formatter.WriteEndPrimitive();
        }

        private static void WritePrimitiveUInt32(IFormatter formatter, IReadOnlyList<object> metadata, object instance)
        {
            formatter.WriteBeginPrimitive(metadata[MetadataIndexes[11]]);
            formatter.Writer.WriteUInt32((UInt32)instance);
            formatter.WriteEndPrimitive();
        }

        private static void WritePrimitiveUInt64(IFormatter formatter, IReadOnlyList<object> metadata, object instance)
        {
            formatter.WriteBeginPrimitive(metadata[MetadataIndexes[12]]);
            formatter.Writer.WriteUInt64((UInt64)instance);
            formatter.WriteEndPrimitive();
        }

        private static void WritePrimitiveUInt16(IFormatter formatter, IReadOnlyList<object> metadata, object instance)
        {
            formatter.WriteBeginPrimitive(metadata[MetadataIndexes[13]]);
            formatter.Writer.WriteUInt16((UInt16)instance);
            formatter.WriteEndPrimitive();
        }

        private static void WritePrimitiveDateTime(IFormatter formatter, IReadOnlyList<object> metadata, object instance)
        {
            formatter.WriteBeginPrimitive(metadata[MetadataIndexes[14]]);
            formatter.Writer.WriteDateTime((DateTime)instance);
            formatter.WriteEndPrimitive();
        }

        private static void WritePrimitiveGuid(IFormatter formatter, IReadOnlyList<object> metadata, object instance)
        {
            formatter.WriteBeginPrimitive(metadata[MetadataIndexes[15]]);
            formatter.Writer.WriteGuid((Guid)instance);
            formatter.WriteEndPrimitive();
        }

        private static void WritePrimitiveTimeSpan(IFormatter formatter, IReadOnlyList<object> metadata, object instance)
        {
            formatter.WriteBeginPrimitive(metadata[MetadataIndexes[16]]);
            formatter.Writer.WriteTimeSpan((TimeSpan)instance);
            formatter.WriteEndPrimitive();
        }

        private static void WritePrimitiveUri(IFormatter formatter, IReadOnlyList<object> metadata, object instance)
        {
            formatter.WriteBeginPrimitive(metadata[MetadataIndexes[17]]);
            formatter.Writer.WriteUri((Uri)instance);
            formatter.WriteEndPrimitive();
        }
    }
}
